sort:    
  - name: Get started
    path: /get_started.md

  - name: How to use TEA Party app
    path: /how_to_use_TEA_Party.md

  - name: Three tier architecture
    path: /3_tier_architecture.md

  - name: Code walkthrough
    path: /code_walkthrough.md
 
  - name: The magic of TEA state machine
    path: /magic_of_state_machine.md

  - name: The magic of WebAssembly
    path: /magic_of_wasm.md


